name: Simple Workflow

# Trigger the workflow on push events to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest version of Ubuntu

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3  # Checks out the repository code (latest v3 version)

    - name: Print "Hello, world!"
      run: echo "Hello, world!"  # Print "Hello, world!" to the GitHub Actions logs

- name: Print "Hello, GitHub Actions!"
      run: echo "Hello, GitHub Actions!"  # This step runs the echo command in the workflow

      